CREATE DATABASE CINEMIPELICULA

USE CINEMIPELICULA

CREATE TABLE PELICULA
(ID_PELICULA VARCHAR(10) PRIMARY KEY,
TITULO VARCHAR(50) NOT NULL,
FECHA VARCHAR(10) NOT NULL,
ID_NACION_P INT NOT NULL,
ID_PROD_P INT NOT NULL,
ID_EMPL_P INT NOT NULL)
GO

INSERT INTO PELICULA VALUES('1', 'Titanic', '10/10/1996',1,2,240)
INSERT INTO PELICULA VALUES('2', 'Star Wars','08/06/1999',2,3,240)
INSERT INTO PELICULA VALUES('520', 'El señor de los anillos','08/06/1999',3,4,240)

CREATE TABLE DIRECTOR
(ID_DIRECTOR INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
ID_NACION_D VARCHAR(30) NOT NULL,
ID_EMPLE_D INT NOT NULL)
GO

CREATE TABLE PELI_DIRECTOR
(ID_PELICULA INT NOT NULL,
ID_DIRECTOR INT,
PRIMARY KEY(ID_PELICULA, ID_DIRECTOR))
GO

CREATE TABLE EJEMPLAR
(NRO_EJEMPLAR INT PRIMARY KEY,
ID_PELI_E INT NOT NULL,
ID_ESTADO_E INT)
GO

CREATE TABLE ESTADO
(ID_ESTADO INT PRIMARY KEY NOT NULL,
TIPO_ESTADO VARCHAR(30) NOT NULL)
GO

CREATE TABLE ACTOR 
(ID_ACTOR INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50)NOT NULL,
SEXO CHAR (1)NOT NULL,
ID_NACION_A INT NOT NULL,
ID_EMPL_A INT NOT NULL)
GO

CREATE TABLE TIPO
(ID_TIPO INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(50))
GO

CREATE TABLE PELI_ACTOR
(
ID_PELI_AC INT PRIMARY KEY,
ID_PELIA VARCHAR(10) NOT NULL,
ID_ACTORP INT NOT NULL,
ID_TIPO INT NOT NULL)
GO

CREATE TABLE NACIONALIDAD
(ID_NACIONALIDAD INT PRIMARY KEY NOT NULL,
NOMBRE_NACIONALIDAD VARCHAR (30)NOT NULL)
GO

INSERT INTO NACIONALIDAD VALUES(1, 'Estados Unidos');
INSERT INTO NACIONALIDAD VALUES(2, 'Alemania');
INSERT INTO NACIONALIDAD VALUES(3, 'Reino Unido');
INSERT INTO NACIONALIDAD VALUES(4, 'Francia');
INSERT INTO NACIONALIDAD VALUES(5, 'Argentina');

CREATE TABLE DETALLE
(ID_DETALLE INT PRIMARY KEY NOT NULL,
FECHA_FINAL DATE NOT NULL,
FECHA_RET DATE NOT NULL,
NRO_EJEMPLAR_D INT NOT NULL,
ID_ALQUILER_D INT)
GO

CREATE TABLE ALQUILER
(ID_ALQUILER INT PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
CEDULA_CLIENTE INT NOT NULL,
ID_EMPL_A INT NOT NULL)
GO

CREATE TABLE EMPLEADO
(ID_EMPLEADO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CLAVE VARCHAR(20) NOT NULL)
GO

INSERT INTO EMPLEADO VALUES(240,'Jose Angel','ci4pelicula')
SELECT * FROM EMPLEADO

CREATE TABLE PRODUCTORA
(ID_PRODUCTORA INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
ID_EMPLEADO INT NOT NULL)
GO

INSERT INTO PRODUCTORA VALUES('1', 'Disney', '963')
INSERT INTO PRODUCTORA VALUES('2', 'Sony', '450')
INSERT INTO PRODUCTORA VALUES('3', 'Universal', '690')
INSERT INTO PRODUCTORA VALUES('4', 'Marvel', '316')

CREATE TABLE TELEFONO_CLIENTE
(ID_TELEFONO INT PRIMARY KEY NOT NULL,
TELEFONO_CLIENTE VARCHAR(15),
CEDULA_CLIENTE INT NOT NULL)
GO

CREATE TABLE CLIENTE 
(CEDULA INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
ID_SOCIO INT NOT NULL,
ID_EMPLE_C INT NOT NULL)
GO

--CREATE TABLE CLIENTE_ALQUILER
--(CEDULA_CLIENTE INT,
--ID_ALQUILER INT,
--PRIMARY KEY(CEDULA_CLIENTE, ID_ALQUILER))
--GO

CREATE TABLE SOCIO 
(ID_SOCIO INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (50) NOT NULL)
GO

CREATE TABLE CASTIGO 
(ID_CASTIGO INT PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
VALOR INT NOT NULL,
ID_DETALLE INT NOT NULL)
GO

CREATE TABLE DIRECCION
(ID_DIRECCION INT PRIMARY KEY NOT NULL,
CEDULA_CLIENTE INT,
ID_CIUDAD INT NOT NULL,
DIRECCION VARCHAR (30) NOT NULL
)
GO

CREATE TABLE CIUDAD
(ID_CIUDAD INT PRIMARY KEY NOT NULL,
NOMBRE_CIUDAD VARCHAR (30) NOT NULL)
GO
 
 -- SE CREAN LAS DIFERENTES RELACIONES ENTRE TABLAS --

 ALTER TABLE PELICULA ADD FOREIGN KEY (ID_NACION_P) REFERENCES NACIONALIDAD(ID_NACIONALIDAD)
 GO

 ALTER TABLE PELICULA ADD FOREIGN KEY (ID_PROD_P) REFERENCES PRODUCTORA (ID_PRODUCTORA)
 GO

 ALTER TABLE PELICULA ADD FOREIGN KEY (ID_EMPL_P) REFERENCES EMPLEADO (ID_EMPLEADO)
 GO

 ALTER TABLE PELI_ACTOR ADD FOREIGN KEY (ID_PELIA) REFERENCES PELICULA (ID_PELICULA)
 GO

 ALTER TABLE PELI_ACTOR ADD FOREIGN KEY (ID_ACTORP) REFERENCES ACTOR (ID_ACTOR)
 GO

 ALTER TABLE PELI_ACTOR ADD FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO)
 GO

 ALTER TABLE ACTOR ADD FOREIGN KEY (ID_NACION_A) REFERENCES NACIONALIDAD(ID_NACIONALIDAD)
 GO

 ALTER TABLE ACTOR ADD FOREIGN KEY (ID_EMPL_A) REFERENCES EMPLEADO (ID_EMPLEADO)
 GO

  ALTER TABLE DIRECTOR ADD FOREIGN KEY (ID_EMPLE_D) REFERENCES EMPLEADO (ID_EMPLEADO)
 GO

  ALTER TABLE DIRECTOR ADD FOREIGN KEY (ID_NACION_D) REFERENCES NACIONALIDAD(ID_NACIONALIDAD)
 GO

 ALTER TABLE PELI_DIRECTOR ADD FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA)
 GO

 ALTER TABLE PELI_DIRECTOR ADD FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR (ID_DIRECTOR)
 GO

 ALTER TABLE EJEMPLAR ADD FOREIGN KEY (ID_PELI_E) REFERENCES PELICULA (ID_PELICULA)
 GO

 ALTER TABLE EJEMPLAR ADD FOREIGN KEY (ID_ESTADO_E) REFERENCES ESTADO (ID_ESTADO)
 GO

 ALTER TABLE DETALLE ADD FOREIGN KEY (NRO_EJEMPLAR_D) REFERENCES EJEMPLAR (NRO_EJEMPLAR)
 GO

 ALTER TABLE DETALLE ADD FOREIGN KEY (ID_ALQUILER_D) REFERENCES ALQUILER (ID_ALQUILER)
 GO

 ALTER TABLE ALQUILER ADD FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE (CEDULA)
 GO

 ALTER TABLE ALQUILER ADD FOREIGN KEY (ID_EMPL_A) REFERENCES EMPLEADO (ID_EMPLEADO)
 GO

 ALTER TABLE CLIENTE ADD FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO)
 GO

 ALTER TABLE CLIENTE ADD FOREIGN KEY (ID_EMPLE_C) REFERENCES EMPLEADO (ID_EMPLEADO)
 GO

 ALTER TABLE TELEFONO_CLIENTE ADD FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE (CEDULA)
 GO

 ALTER TABLE DIRECCION ADD FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE (CEDULA)
 GO

 ALTER TABLE DIRECCION ADD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD)
 GO

 ALTER TABLE CASTIGO ADD FOREIGN KEY (ID_DETALLE) REFERENCES DETALLE (ID_DETALLE)
 GO

 ---Store Procedures---

 --Llenar Combo por Nacionalidad
CREATE PROCEDURE USP_Nacionalidad_Pelicula
 AS
	BEGIN
		SELECT ID_NACIONALIDAD    Codigo,
			NOMBRE_NACIONALIDAD  Nombre
		FROM NACIONALIDAD
	ORDER BY Nombre
	--EXEC USP_Nacionalidad_Pelicula
END
GO

--Llenar Combo Por Productora
 CREATE PROCEDURE USP_Productora_Pelicula
 AS
	BEGIN
		SELECT ID_PRODUCTORA    Codigo,
			NOMBRE  Nombre
		FROM PRODUCTORA
	ORDER BY Nombre
	--EXEC USP_Productora_Pelicula
END
GO

--Buscar una Película por Código
CREATE PROCEDURE USP_PeliculaBuscarXCodigo
@strCodigo int
AS
	BEGIN
		SELECT ID_PELICULA	   Codigo,
			   TITULO		   Titulo,
			   FECHA           Fecha,
			   ID_NACION_P     Nacionalidad,
			   ID_PROD_P       Productora,
			   ID_EMPL_P	   Empleado
		FROM PELICULA
		WHERE ID_PELICULA = @strCodigo
		--EXEC USP_PeliculaBuscarXCodigo 1
END
GO

--Insertar una Pelicula
CREATE PROCEDURE USP_Pelicula_Grabar
@strCodigo varchar(10),
@strTitulo varchar(50),
@strFecha varchar(10),
@intNac int,
@intPro int,
@intIdEmp int
AS
	BEGIN 
		IF EXISTS(SELECT * FROM PELICULA 
				WHERE ID_PELICULA = @strCodigo)
		BEGIN
			SELECT -1 AS Rpta
			Return
		end
		ELSE
		  BEGIN
			BEGIN TRANSACTION tx
			INSERT INTO PELICULA
				VALUES(@strCodigo, @strTitulo, 
				@strFecha, @intNac,
				@intPro, @intIdEmp);
		IF (@@ERROR > 0)
			BEGIN
				ROLLBACK TRANSACTION tx
				SELECT 0 AS Rpta
				Return
		END
			COMMIT TRANSACTION tx
			SELECT @strCodigo AS Rpta --SELECT @@identity AS rpta
			Return
		END
		--EXEC USP_Pelicula_Grabar 3,'Capitan America','02/26/2012', 2,1,240
		--select * from PELICULA
	END
GO

--Llenar Grid - Peliculas --
Create Procedure USP_PeliculaxNacion
@intNac int
AS
	BEGIN
		SELECT PELICULA.ID_PELICULA    Codigo, 
			PELICULA.TITULO            Titulo, 
			PELICULA.FECHA			   FechaE, 
			NACIONALIDAD.NOMBRE_NACIONALIDAD    Nacionalidad, 
			EMPLEADO.NOMBRE			    NombreE
			FROM PELICULA
			INNER JOIN NACIONALIDAD ON PELICULA.ID_NACION_P = NACIONALIDAD.ID_NACIONALIDAD
			INNER JOIN EMPLEADO ON PELICULA.ID_EMPL_P = EMPLEADO.ID_EMPLEADO
		END
		-- Exec USP_PeliculaxNacion 1
		-- SELECT * FROM NACIONALIDAD
GO